#!/bin/bash

# Test script for Fitness Tracker Frontend
# This script will start the application and provide testing instructions

echo "🏋️  Fitness Tracker - Frontend Test Guide"
echo "=========================================="
echo ""
echo "Starting the application..."
echo ""
echo "Run the following command to start:"
echo "  docker-compose up --build"
echo ""
echo "Or with database seeding:"
echo "  SEED_DB=true docker-compose up --build"
echo ""
echo "📋 Testing Checklist:"
echo ""
echo "1. Authentication Tests:"
echo "   ✓ Open browser to http://localhost:8000"
echo "   ✓ Try signing up with a new account"
echo "   ✓ Test login with: john.doe@example.com / password123 (if seeded)"
echo "   ✓ Verify logout functionality"
echo ""
echo "2. My Workouts Tab:"
echo "   ✓ View list of personal workouts"
echo "   ✓ Click on a workout to see details"
echo "   ✓ Check public/private badges display"
echo ""
echo "3. Create Workout Tab:"
echo "   ✓ Fill in workout title and date"
echo "   ✓ Add multiple exercises"
echo "   ✓ Add multiple sets to each exercise"
echo "   ✓ Toggle public/private option"
echo "   ✓ Submit and verify creation"
echo "   ✓ Test removing exercises and sets"
echo ""
echo "4. Public Feed Tab:"
echo "   ✓ View all public workouts"
echo "   ✓ Click to view workout details"
echo "   ✓ Verify you can see other users' public workouts"
echo ""
echo "5. Responsive Design:"
echo "   ✓ Resize browser window"
echo "   ✓ Test on mobile viewport"
echo "   ✓ Verify all features work on small screens"
echo ""
echo "6. Error Handling:"
echo "   ✓ Try logging in with wrong credentials"
echo "   ✓ Try creating workout without exercises"
echo "   ✓ Try submitting forms with missing fields"
echo ""
echo "🔗 Useful URLs:"
echo "   Frontend: http://localhost:8000"
echo "   API Docs: http://localhost:8000/docs"
echo "   API: http://localhost:8000/workouts/"
echo ""
echo "📝 Test Users (if database is seeded):"
echo "   User 1: john.doe@example.com / password123"
echo "   User 2: jane.smith@example.com / password123"
echo ""

